### ISSUE TITLE
Output `hosts` records to file

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/nitro#111]
This could be a file in the `~/.nitro` directory.

The reason for this is that if you using apps such as [switch hosts](https://oldj.github.io/SwitchHosts/) or [gas mask](https://github.com/2ndalpha/gasmask) you can use the file as a remote and have it combine with other custom host records.

This goes hand in hand with #110

**Comment by lukeholder** [comment]
A note for others who use gasmask, I had to turn of 'override external modifications' in gasmask preferences to let nitro edit the main host file. Gasmask was monitoring it and reverting any changes made by 3rd parties.

**Comment by nfourtythree** [comment]
@jasonmccallister would be amazing to get this now that #110 is possible!

**Comment by jasonmccallister** [comment]
Maybe I am an edge case, which would not be the first time :), but I have never used tools like this for hosts files. Is this an edge case? I'm curious how we would work this into a config so we know when we should write to the external file. 

Otherwise would this require everyone to use a tool like this?
