### ISSUE TITLE
Store editor choice in nitro for use with `nitro edit`

### ISSUE THREAD

**Issue by nfourtythree** [craftcms/nitro#114]
It would be nice to be able to set the editor choice within `nitro-dev.yaml` it is a little less heavy-handed than setting it globally in your bash profile.

Keeping the bash profile as a fallback would work nicely

**Comment by brandonkelly** [comment]
See the tip in the [edit](https://github.com/craftcms/nitro#edit) command docs.

**Comment by jasonmccallister** [comment]
Should this be closed since the EDITOR is a shell configuration?

**Comment by nfourtythree** [comment]
I agree EDITOR in the shell should be the default/fallback. But the reason for this FR is to be able to add it into the nitro config so I could set it to something else e.g. sublime, atom, phpstorm etc without being heavy handed and having to overwrite it for all of my shell things. 

Does that make sense?

**Comment by brandonkelly** [comment]
I’m not a huge fan of this FR, since your preferred editor is a _personal_ choice, not a part of machine configuration (or something you’d want to set differently from one machine to the next).

I just updated the [`edit`](https://github.com/craftcms/nitro#edit) docs to mention that you can open the config file using the system’s `open` command, which will open with the system’s default `.yaml` editor.
