### ISSUE TITLE
Request entity too large error from Nginx when uploading >1MB file

### ISSUE THREAD

**Issue by rmales** [craftcms/nitro#126]
When I try to upload a file to a new Craft site in Nitro I get a `413 (Request Entity Too Large)` error from Nginx (which incidentally the Craft uploader Javascript does not catch). I'm sure I could fix this by modifying the Nginx config, but I assume Nitro should come with reasonable defaults for Craft out of the box.

**Comment by clarknelson** [comment]
I'm curious what you typically set this to? I set to 10MB and larger files I try to offload to CDNs.

**Comment by jasonmccallister** [comment]
Since this is a development environment, I set the size to 100MB. Will be included in 1.0.0-beta.3.

**Comment by clarknelson** [comment]
perfect, thank you!

**Comment by khalwat** [comment]
IMO you should be doing:

```
    # Disable limits on the maximum allowed size of the client request body
    client_max_body_size 0;
```

...instead. This then allows Craft to specify any upload limits with [maxUploadFileSize](https://docs.craftcms.com/v3/config/config-settings.html#maxuploadfilesize)

There's no danger in leaving it unrestricted, especially for a local dev environment, if Craft also is laying on a setting that limits it.

Otherwise you're just kicking the can down the road in terms of what is "big enough" of a file size.

c.f.: https://github.com/nystudio107/nginx-craft/blob/master/sites-available/somedomain.com.conf#L52
