### ISSUE TITLE
Home folder transition

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#134]
Look at moving main sites folder from /nitro/sites directly into the ubuntu home folder.

Sites go in:

    /home/ubuntu/sites/x.tld

And other custom mounts in:

    /home/ubuntu/*

**Comment by brandonkelly** [comment]
This will reduce confusion i.e. #114

**Comment by jasonmccallister** [comment]
I just wrapped up this change and everything looks good to go! 

There is one issue going from `1.0.0-beta.2` or previous machines. Since we moved the sites to `/home/ubuntu/sites` when adding a site after upgrading there is a error mounting the site:

```
$nitro add plugins-dev
What should the hostname be? [plugins-dev] plugins.nitro
Where is the webroot? [web]
Added plugins.nitro to config file
Apply changes from config? [yes]
Error: exit status 127
```

This is something we can resolve in the upgrade guide. The steps to resolve are:

1. `nitro ssh`
2. `mkdir sites`
3. `nitro apply`
