### ISSUE TITLE
Facility or best practice for customizing nginx config

### ISSUE THREAD

**Issue by mattstein** [craftcms/nitro#18]
Anyone comfortable with nginx will most likely want to tailor its config with project-specific considerations like cache fragments or custom headers or whatever. Ideally there would be either a specific, prescribed way of doing that or a recommended best practice so the end user could keep their config versioned and not create a Nitro hairball. (Which would smell terrible.)

**Comment by jasonmccallister** [comment]
@mattstein would these types of changes be setup for local development? Maybe to test a configuration before deployment? If that is the case, the user can `nitro ssh` and modify the template. 

Perhaps we should also set another directory where configs can be placed and loaded by nginx?

**Comment by mattstein** [comment]
@jasonmccallister Yep! One case I imagine is testing [Blitz’s static cache handoff](https://putyourlightson.com/plugins/blitz#nginx).

> Perhaps we should also set another directory where configs can be placed and loaded by nginx?

This seems ideal—I know I’m on my own if I break it, but I’d prefer to version control any customizations I make and not lose them when I nuke the VM.

**Comment by jasonmccallister** [comment]
We have a pretty solid Nginx configuration with Nitro 2 that is now based on the [craftcms/docker](https://github.com/craftcms/docker) images so I'm not sure this is needed anymore?

**Comment by mattstein** [comment]
I could personally live without it, but there are cases where it’d be nice to test something nginx- or Apache-dependent locally rather than resorting to another dev environment or just crossing your fingers in staging/production.

I use the example of [Blitz’s static cache setup](https://putyourlightson.com/plugins/blitz#nginx) because I expect that’s fairly common in the community.

But again: a nice-to-have for me and not a need-to-have FWIW.

**Comment by therealpecus** [comment]
I have a few use cases:
- porting rules that a production website implements as .htaccess
- rewriting static assets for immutability (e.g. `styles.234fss43.css` to `styles.css`)

The best approach (I do not know if it's feasible) would be for nginx to include by default a `nginx.local.conf` file from the user craft or web directory (and fail silently if not available). This allows to have the container completely volatile but persist the configuration

**Comment by jasonmccallister** [comment]
@therealpecus I think this approach makes a lot of sense and matches what we have setup for PHP extensions (https://craftcms.com/docs/nitro/2.x/php-settings.html#manually-overriding-php-settings). 

I made these changes locally:

1. Modified the `default.conf` at `/etc/nginx/conf.d/default.conf` (will need to be updated in https://github.com/craftcms/docker and https://github.com/craftcms/nitro/blob/main/command/apply/internal/nginx/nginx.go#L19)
2. Added the `include /app/nginx.nitro.conf;` with the content below:

```
location ~ ^/testing {
    default_type text/html;
    return 200 'Testing custom config!';
}
```

Some things to consider are if the nginx configuration is incorrect, it will not load and the proxy will just load a blank page. So  it might be worth adding some kind of validation to the nginx configuration. 

Nginx does have a way to test the config using `nginx -c /app/nginx.nitro.conf  -t` but will fail since it needs all of the config loaded properly.

**Comment by jasonmccallister** [comment]
We just tagged [1.2.7](https://github.com/craftcms/docker/blob/main/CHANGELOG.md#127---2021-04-22) of the Docker images where `dev` containers will look for configuration file at `/app/nitro.conf`. If you are using a web root other than `web` for the sites container it will not get picked up until the next release of Nitro.

**Comment by angrybrad** [comment]
For 2.0.9 we're going to improve on this so that if a nitro.conf exists at the root of the project, you'll be able to override the entire default server block (similar to what's in https://github.com/craftcms/nitro/blob/develop/command/apply/internal/nginx/nginx.go) instead of an include in the middle of it.

We'll need to document the few required configs from that block that are required for nitro to operate.

**Comment by hiasl** [comment]
@angrybrad @jasonmccallister If I understand this correctly, I can place a nitro.conf in my project root and it will be used instead of the default host configuration, right? Is this documented somewhere? How do I get the default content of this file, which i can then modify? Wouldn't it be a good idea to get a `nitro <something>` command which dumps the config into this file? thanks!

**Comment by magicspon** [comment]
Is there any docs on this?  

I'm using headless craft and I need to be able to pull images into a THREE.js canvas.

I added this to my nginx conf on forge which does the job.  I need to be able to replicate this with nitro..

```
    location ~ \.(avifs?|bmp|cur|gif|ico|jpe?g|jxl|a?png|svgz?|webp) {
            if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
     }
     if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
     }
    }
 ```

**Comment by mattstein** [comment]
@hiasl you’re partly right. You can put any file _ending_ in `nitro.conf`—so `my-nitro.conf`, `foo.nitro.conf`, `nitro.conf`, etc.—in your project root and Nitro will include those [here](https://github.com/craftcms/nitro/blob/develop/command/apply/internal/nginx/nginx.go#L21:L21) as part of its own configuration. The challenge is that your config does _not_ replace Nitro’s, and that whatever you add could be overwritten by everything in Nitro’s configuration that follows. We’ll be changing how this works in Nitro 3 so it’s possible to completely control that nginx configuration.

@magicspon it looks like at least some of those file type handlers would clash [with Nitro’s](https://github.com/craftcms/docker/blob/main/nginx/craftcms/general.conf#L15), so at best that could only work partially with Nitro 2.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
