### ISSUE TITLE
Add the ability to execute commands remote over ssh 

### ISSUE THREAD

**Issue by yanickrecher** [craftcms/nitro#189]
It would be helpful to run a bash command with `nitro ssh` command.

as Example:

``` 
nitro ssh -e 'docker ps --format "{{.Names}}"' 
```

...or without a flag (how it is usually working with ssh):
``` 
nitro ssh 'docker ps --format "{{.Names}}"' 
```

I would expect to get the result direct in the terminal of the Host System.

thank you

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2). We made it a lot easier to run commands in the sites containers by adding the [`ssh`](https://craftcms.com/docs/nitro/2.x/commands.html#ssh) command and the [`craft`](https://craftcms.com/docs/nitro/2.x/commands.html#craft) command. Going to mark this as resolved since we moved from Multipass to Docker. Thank you!
