### ISSUE TITLE
Running init with an existing config installs PHP 7.4

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/nitro#194]
### Description
When using an existing configuration file, `nitro init` will install PHP 7.4 even if the config file has the version set as "7.3".

### Steps to reproduce

1. Create a machine with PHP 7.3
2. Destroy the machine
3. Change the version to 7.4 in the config
4. Run `nitro init` and see that PHP 7.4 is installed by default

### Additional info

- Nitro version: beta.10
- Multipass version: all

**Comment by RedLucas** [comment]
hey, I don't know why but I'm actually still getting this issue. I am up to date on 1.1.1. It was not finding the 7.3 service and defaulting to 7.4 when I already had global config. I deleted the global config and tried it from scratch and it worked. I was wondering what the resolution of this was, or if it was just closed because nobody else reported it.
