### ISSUE TITLE
rpc error when using any of the `nitro php ...` commands

### ISSUE THREAD

**Issue by andrewmenich** [craftcms/nitro#201]
### Description

Using any of the `nitro php ...` commands, I received the following error:

`Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.64.2:50051: connect: connection refused"`

I've restarted nitro as well as my physical machine without luck. Any help is appreciated!

### Steps to reproduce

1. `nitro php iniget max_input_vars`

### Additional info

- Nitro version: 1.0.0
- Multipass version: 1.4.0 mac
- Host OS: darwin (macOS Mojave 10.14.5)

My hosts file is as follows:
```
127.0.0.1        localhost

255.255.255.255  broadcasthost

::1              localhost

192.168.64.2     craft.test clientname.test
```

**Comment by jasonmccallister** [comment]
@andrewmenich I am assuming you upgraded from an earlier version of Nitro? There were some changes with the RC's that introduced a new API that runs on the virtual machine. This API allows us to treat Nitro as more of a CLI and the majority of the logic will be moved to the API going forward.

However, this indicates the API is not running on your machine and these steps will install and setup the API for you:

1. Login with `nitro ssh`
2. Run `wget https://raw.githubusercontent.com/craftcms/nitro/master/nitrod.sh -O /tmp/nitrod.sh && sudo bash /tmp/nitrod.sh`
3. Exit with `exit` and run `nitro restart`
4. Try `nitro php iniget max_input_vars` and you should see the value in the terminal

This issue was cased by the `nitro refresh` command which will be removed going forward and updates will happen automatically in the background when communicating with the API.

Let me know if that resolves your issue!

**Comment by andrewmenich** [comment]
That did the trick! Thanks, Jason. I had indeed upgraded from an earlier version.

**Comment by a-am** [comment]
@jasonmccallister I tried the suggestion and still continue to receive `Error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.64.3:50051: connect: connection refused"` after trying to update `upload_max_filesize` with `nitro php iniset upload_max_filesize 20M `.
