### ISSUE TITLE
Hostnames ending with '.localhost' don't work

### ISSUE THREAD

**Issue by alinnert** [craftcms/nitro#202]
### Description

It took me some time to get my site up running using Nitro. It seems like Nitro (or Multipass? Or Hyper-V?) doesn't allow hostnames to end with `.localhost`. At work we're using different virtual machines (for different kind of projects) but hostnames like `my-project.localhost` work just fine there. So, I expected this to be true for Nitro as well. In both cases the host is a Windows machine, so I don't think that's the problem.

I don't know if there's something that can be done about this, or if it's worth doing something about it, or if other hosts are even affected by this. But I think it's at least worth mentioning this in the docs, right? I've debugged this problem from both sides (does my hosts file work? Is nginx configured correctly? etc.) This is where I've noticed that nginx doesn't even seem to receive requests to `something.localhost`. But I don't know why.

The advantage of `.localhost` is that chromium-based browsers recognize `localhost` as a TLD and don't open your search engine with the address as the search term by default.

### Steps to reproduce

- Edit `nitro-dev.yaml` and change a hostname to `my-project.localhost`
- Run `nitro apply`

Accessing `my-project.localhost` in the browser isn't possible. It says the site is not reachable.

Run the steps above again but change the hostname to `my-project.local` (or anything else) and the site is accessible in the browser.

### Additional info

- Nitro version: 1.0.1
- Multipass version: 1.4.0+win

**Comment by jasonmccallister** [comment]
@alinnert I did a little bit of research and discovered the TLD `.localhost` resolves back to `127.0.0.1` by default due to an IETF RFC. Since Multipass creates a virtual network and assigned a new IP like `192.168.x.x` and does not use `127.0.0.1`, the `.localhost` TLD will not resolve to the IP address of the Nitro instance.

Found a write up here https://en.wikipedia.org/wiki/.localhost, I'm sure there are more technical articles but that is a good reference.
