### ISSUE TITLE
Initialisation fails to determine IP address

### ISSUE THREAD

**Issue by designkarma** [craftcms/nitro#224]
### Description

First time trying Nitro but can't get past initialisation...

```
Initialize the primary machine now? [yes]
How many CPU cores? [2]
How much memory? [4G]
How much disk space? [40G]
Which version of PHP? [7.4]
Which database engine? [mysql] 
Which version of mysql? [5.7] 
Applying the changes now...
launch failed: The following errors occurred:
failed to determine IP address
Error: exit status 2
```

### Steps to reproduce

Just following the installation steps outlined [here](https://craftcms.com/docs/nitro/installation.html#installing-nitro), and following the prompts to create my first machine.

### Additional info

- Nitro version: 1.1.1
- Multipass version: 1.5.0

**Comment by jasonmccallister** [comment]
@designkarma are you running a proxy or VPN on your host machine?

**Comment by jasonmccallister** [comment]
We just released Nitro 2 where we switched from Multipass to Docker and added a ton of new features. Please see the [announcement for more details](https://craftcms.com/blog/nitro-2).

This issue was specific to Multipass so we are going to close this out. Please see the documentation on upgrading from [Nitro 1](https://craftcms.com/docs/nitro/2.x/upgrade.html).
