### ISSUE TITLE
 [2.0.0-beta.2]  /app/storage isn't writable by PHP. Please fix that. 

### ISSUE THREAD

**Issue by hodgins96** [craftcms/nitro#240]
### Description
When setting up new new craft project error occurs.
/app/storage isn't writable by PHP. Please fix that.  
Can be fixed by chmod 777 but that shouldn't be the case 

### Steps to reproduce

1. nitro create
2. nitro craft setup

### Additional info

- Nitro version: 2.00-beta.2
- OS: Pop!_OS 20.10 x86_64 
- Kernal: 5.8.0-7630-generic 
- Docker: 20.10.2

**Comment by jasonmccallister** [comment]
Thank you for the report @hodgins96. This is a little tricky to handle automatically across operating systems, specifically macOS and Linux due to the underlying container support. We have a section on [setting file permissions](https://craftcms.com/docs/3.x/installation.html#step-2-set-the-file-permissions) in the documentation. However, it would be nice to handle these permissions automatically. 

I'm going to run some more tests on my Pop!_OS 20.04 machine and work better supporting file permissions as well as local HTTPS support.

**Comment by MattWilcox** [comment]
Yep, a manual `sudo chmod -R 777 .env composer.* config storage vendor web/cpresources` allowed me to install and run.

**Comment by jasonmccallister** [comment]
Yeah, the main concern forcing those permissions is Windows/WSL2 support... The permissions get a little wonky in WSL... https://askubuntu.com/questions/911804/ubuntu-for-windows-10-all-files-are-own-by-root-and-i-cannot-change-it

**Comment by MattWilcox** [comment]
Yeah, 777 is a bad code smell anyway. Ideally this would be fixed via User rather than just nixing any sort of permission protections which is what 777 is doing. But, I'm totally ignorant of how VMs work with mounted host file systems. All I know is that this is not an issue on OSX when running Nitro1 (which is a Ubuntu VM with the host filesystem mounted inside it?)

**Comment by jasonmccallister** [comment]
On v1, Multipass and `sshfs` take care of the file permissions and we place sites into the `/home/ubuntu/`, in the Docker images we run as the `www-data` user to limit permissions... I'm sure we can get there, just want to be cautious.

**Comment by jasonmccallister** [comment]
@hodgins96 and @MattWilcox we are going to close this ticket out since different environments make this really tricky. Thank you for the report. If you are having file permissions issues this will walk you through the setup: https://craftcms.com/docs/3.x/installation.html#step-2-set-the-file-permissions

**Comment by MattWilcox** [comment]
What would the right user be though? I have no idea what Docker is doing, but setting a bunch of things to 777 isn't great, and does require adjusting GIT so that it does not store permissions; otherwise they're going to end up 777 on production.

**Comment by mhgbrown** [comment]
This worked for me without having to open everything up to 777.

```bash
# change perms on host
sudo chmod -R 774 .env composer.* config storage vendor web/cpresources

# log into container as root
docker exec -u 0 -it <site nginx container id> sh
# install usermod and groupmod
apk --no-cache add shadow
# change group id of www-data to match host group id
groupmod -g 1000 www-data

# restart nitro on host
nitro restart
```
