### ISSUE TITLE
Dynamically spin project containers up / down

### ISSUE THREAD

**Issue by khalwat** [craftcms/nitro#346]
Currently, Nitro is all or nothing in terms of starting up projects in typical usage (yes, I know there's a command for starting a single site).

I think there might be a better way to handle it.

Since Nitro already has a proxy running, and knows about all of the sites on the machine, it'd be nice if containers associated with a project are lazily started up when any request for that project hits the proxy.

This would prevent the inefficient memory use and speed hit of starting up all project containers at once.

And a garbage collection task could be running that would spin down the containers of any projects that hadn't been hit in a specified period of time.

 It's very common for an individual to have dozens of projects over time, but typically only one or two are actively being worked on at any one time.

This would make it all work transparently, without having to allocate huge amounts of memory to Docker.

**Comment by jasonmccallister** [comment]
Just a few thoughts on this...

> Currently, Nitro is all or nothing in terms of starting up projects in typical usage (yes, I know there's a command for starting a single site).

The `nitro start my-site.nitro` will only spin up the proxy, databases, and individual site to reduce the number of web containers running, but those do not consume as much resources (~ 150-200 Mb) as the databases.

> Since Nitro already has a proxy running, and knows about all of the sites on the machine, it'd be nice if containers associated with a project are lazily started up when any request for that project hits the proxy.

We did discuss this functionality at first, but because the proxy container is running inside of the Docker network there are two ways to handle this from the top of my head:

1. Expose some kind of API on the Nitro binary that is always running on the host machine for the proxy to send requests (securely). This would make Nitro more fragile across OS platforms as we would need to handle running a daemon (not impossible but adds an extra step)
2. Expose the Docker API over HTTP versus the default socket. Its possible and Docker provides a how-to guide but can introduce security concerns.

I'm not sure which one is the best approach but my immediate thought is to lean towards the first option as we control it. The other thing to consider is how we plan on exposing a GUI/UI for the Nitro binary that will include an API - so we will most likely need that functionality. Documented the initial idea and thoughts in https://github.com/craftcms/nitro/issues/349.

> This would prevent the inefficient memory use and speed hit of starting up all project containers at once.

I still have to see performance problems cause by running multiple web containers at a time, most of the performance issues have been with the databases (mysql) and Docker's default resource allocation 2GB.

> It's very common for an individual to have dozens of projects over time, but typically only one or two are actively being worked on at any one time.

This is why we introduced the site arguments to only work on one site at a time.

Just wanted to write some thoughts so they are captured somewhere. Thank you for the FR @khalwat!

**Comment by khalwat** [comment]
Or more simply, `nitro start` could just start the proxy?

Sites could have a flag in terms of how they are started: `lazy` (the default) or `eager` and it'd always load any `eager` sites, and `lazy` sites would be loaded in as needed, and also spun down when not in use.

Site that are `lazy` spin up only when a http request comes in that the proxy intercepts.

If the databases are all in one container, perhaps that's something that could change... I think it's likely that most people are working on one or two things at a time and the ability to section them off would be useful.

The garbage collection task would look for any `eager` sites that hadn't been used in some time, and spin their containers down.

**Comment by angrybrad** [comment]
My first reaction is auto-spinning up and down of containers and garbage collection is a bit of over-engineering?

What's the use-case that we're trying to solve?

Containers are generally lightweight resource-wise. I can't think of a case where someone ran into a Docker resource limitation and shutting down all of their containers except for one resolve it for them.

**Comment by khalwat** [comment]
I've sat there and watched and waited as people fired up Nitro with dozens of projects... and it took longer than seemed reasonable for the one project they wanted to work on.

And then with them all running, it's taking up more memory and CPU cycles than is needed for just the one project they wanted to work on.

So the use-case we're trying to solve is:

- startup time
- memory usage
- CPU usage

I don't see it as over-engineering given that you already have the proxy in place anyway -- but sure, if you want to improve the manual way of doing this, that's an option too.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
