### ISSUE TITLE
`nitro self-update` should default to the current major version

### ISSUE THREAD

**Issue by angrybrad** [craftcms/nitro#356]
Currently if you `nitro self-update` on Nitro v1, you'll get the latest v2 release, which is wholly incompatible with v1.

We should default so that `self-update` sticks to the current major version and add a flag (ala Composer) so that you'd need to explicitly specify you want to jump a major version going forward.

i.e. `nitro self-update -version=2` or some such.

**Comment by jasonmccallister** [comment]
Since we use the GitHub API, there is not r[eally a clean way to filter prereleases from a normal release](https://docs.github.com/en/rest/reference/repos#list-releases) (as a filter) and requires  manually parsing the JSON response. There is a bool key for the release "type" `prerelease` that when we use something like `--dev` it finds the first prerelease and also verifies its greater than the current version.

**Comment by angrybrad** [comment]
> requires manually parsing the JSON response.

Yeah, we'd have to do something like this.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
