### ISSUE TITLE
`nitro create` should prompt the user to install Craft after spinning up containers

### ISSUE THREAD

**Issue by MLCochrane** [craftcms/nitro#365]
### Description
Currently when using `nitro create` it's not terribly clear that you still need to install Craft afterwards. Wondering if this might be helpful for new users to nitro, docker and/or Craft as going through the docs as well as prompts from `create` don't mention the final piece of the puzzle.

Couldn't seem to find any note following the docs here: [Project Setup](https://craftcms.com/docs/nitro/2.x/usage.html#creating-a-new-site-with-nitro-create) or on docs for the command here: [Commands: create](https://craftcms.com/docs/nitro/2.x/commands.html#create).

You can successfully install either through `nitro craft install` or by going to `/admin` but if you don't know to do that and just try to visit your site url (ex. `http://test.nitro/`) you get a 503 and figure you must have missed something. 

Not sure if maybe this would simply be a small documentation change? Or perhaps a second line after `Nitro is up and running 😃`?

**Comment by jayhlee** [comment]
Experiencing the same thing. Based on the [Nitro2 doc](https://craftcms.com/docs/nitro/2.x/usage.html#creating-a-new-site-with-nitro-create), `nitro create` should "prompt you to run `nitro apply` in order to update Nitro’s settings and your hosts file." However, there is no prompt, and going to the newly setup hostname gives a 503 error. 

Even if you `nitro apply`, the hostname URL still throws a 503. In addition, after running `nitro create`, all my other Nitro sites give a 503 as well. Running `nitro update` will get the other Nitro sites back up. But the new site still doesn't load and there isn't a way to set up Craft by going to `/admin`. The only way is to `nitro craft setup`. And even if you're able to `nitro craft setup`, the site still doesn't resolve. It just throws a 404 error.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
