### ISSUE TITLE
Sites unable to connect to DB

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/nitro#372]
### Description
Crating new or adding existing sites as Nitro sites are unable connect to the DB on WSL. Assuming creating a site would setup the .env file correctly, they still cannot connect. Using a MySQL GUI (DBeaver), I can connect to the DB directly and browse, but I guess the .env would need a different host address to connect with as it's running in WSL?

### Steps to reproduce

1. Create new or add site to Nitro
2. Open site, browse CP, or run /admin/install
3. Get 503 error

### Additional info

- Nitro version: 2.0.8
- Docker version: 3.4.0

**Comment by jamiematrix** [comment]
May have fixed it, and I'm not sure why it's working the way it is.

Docker, Nitro, and DBeaver all have MySQL container as being on port 3307 - even the container name has 3307 in it. DBeaver is connected and working on 3307.
Despite all of this, I can create new sites and setup current sites as long as they connect to the database on 3306.

**Comment by jasonmccallister** [comment]
@jamiematrix this is documented on [this page](https://craftcms.com/docs/nitro/2.x/databases.html). Internal database connections use the driver/engines default port (e.g. `3306`) as they are located inside of the containers network. The port set in the config file is only used for creating a unique names (since we support running [more than one database engine at a time](https://craftcms.com/docs/nitro/2.x/multiple-databases.html)) and external access with a GUI. 

I think we need to do a better job at illustrating this going forward, but its not necessarily a bug - unless you are saying the `.env` file was modified by Nitro to use the external versus internal port number?
