### ISSUE TITLE
Web pages do not refresh restarting Craft

### ISSUE THREAD

**Issue by nathansnelgrove** [craftcms/nitro#426]
### Description
Once in a while, in unpredictable fashions, I am unable to preview changes I've made in a template file without restarting Nitro entirely. In accordance with [this SO question](https://craftcms.stackexchange.com/questions/37588/template-and-other-files-do-not-update-with-nitro), I've disabled "use gRCP FUSE for file sharing" in Docker and that seems to have fixed it, but now everything is much slower (of course).

I'm on the latest version of macOS Monterey.

### Steps to reproduce

1. Edit template files in any Craft project. Add an error just to get an error page, where it seems to get consistently stuck for me (but that's not the only time it will get stuck; it's just the most consistent.
2. Attempt to make any changes to your template, even changes that will fix the issue. Note that the error page does not change.
3. Enjoy your life of `nitro restart`. `¯\_(ツ)_/¯`

### Additional info

- Nitro version: 2.0.8
- Docker version: 4.1.1
- macOS 12.0.1, if it helps

**Comment by nathansnelgrove** [comment]
I just ran into this again on an Apple Silicon MacBook Pro. Brand new, basically settings are like they are OOTB. Is there any update on this? Googling the problem led me right back to my own GitHub issue.

**Comment by jasonmccallister** [comment]
@nathansnelgrove there are a few things that can cause this... I would recommend giving this a quick once over https://craftcms.com/docs/nitro/2.x/how-nitro-works.html#docker-performance. 

Personally, I remove all of the file sharing except my users directory as I only ever run docker projects in my directory (see the screenshot below).

Also, you are using Docker 4.1.1 and they are pushing a lot of updates to work on performance for macOS specifically, my version is running 4.7.1.

Docker also released 4.6.0 with a new VirtioFS optional (that is still experimental). Here is the snippet about that feature:

> Enables the new Monterey VirtioFS accelerated directory sharing. This improves I/O performance for operations on volumes shared with '-v'. Note - you must have macOS 12.2 or later and the new Virtualization Framework enabled (via toggle above). We recommend that Intel mac owners use macOS 12.3 for best experience.

It does require macOS 12.2 or later though so that might not work for you. Can you confirm the Docker version and file sharing settings?

<img width="1197" alt="Screen Shot 2022-05-04 at 11 05 33 AM" src="https://user-images.githubusercontent.com/5354908/166711522-cb4141a9-9ede-4bcf-b5d4-4b47549de265.png">

**Comment by nathansnelgrove** [comment]
Thanks @jasonmccallister! I am also running 4.7.1 on my machine. I'll re-enable gRPC FUSE and change the file sharing and experimental features as suggested, and report back if that fixes my problem after a couple days.

**Comment by jasonmccallister** [comment]
Great to hear @nathansnelgrove! We have seen some hangups with the new VirtioFS, but those were on 4.6.0 when it first came out. 

Unfortunately its hard to distinguish what's Nitro versus what is Docker since we try to abstract those complexities away from the end user but glad its working now; although you might have the opposite effect now where the changes are "stale" in the container versus what is on your local filesystem.

**Comment by nathansnelgrove** [comment]
@jasonmccallister that honestly sounds like the same issue I had before, so it'll be interesting to see if that continues. If it does, I'll try disabled VirtioFS and simply restricting shared files. Maybe that will make indexing faster? Who knows. The problem with all these abstractions (not your fault, merely the Docker way) is that it turns these systems into a black box for troubleshooting.

**Comment by jasonmccallister** [comment]
Hi, we are closing this issue as we have decided to retire Nitro, so no additional work will occur on this project. You can read the official blog post here https://craftcms.com/blog/retiring-craft-nitro. We appreciate everyones feedback and involvement and we look forward to refocusing our efforts on Cloud! 

If you're looking for a new local development environment, we recommend DDEV and have a knowledge base article to help you with the transition: https://craftcms.com/knowledge-base/migrating-from-craft-nitro-to-ddev.
